### PR TITLE
baseDir should override file dirname

### PR DESCRIPTION
**Pull request by EnriqueVidal**
Currently if you set a `baseDir` it only prefix the full filepath of the asset instead of overriding it, this makes it so that the `baseDir` replaces the file path if present.

### CODE REVIEW

**Comment by yeojz** [comment]
@EnriqueVidal thanks for the PR.

hmm... this may change the behaviour though... 
This change assumes that we want to flatten the folder directory into a single level image directory...

I think it is a valid use-case, but probably would be better to add a flag to the options to enable this behaviour.

**Comment by EnriqueVidal** [comment]
Got it, will update my PR

**Comment by EnriqueVidal** [comment]
@yeojz Is this a more acceptable implementation? Thanks in advance.

**Comment by yeojz** [comment]
Looks good. Thanks @EnriqueVidal 👍

**Pull request merged**
